apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kyso-nats-js-pvc-kyso-nats-0
  namespace: nats-prod
  labels:
    app.kubernetes.io/name: nats
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
