include:
  - project: 'common/gitlab-ci'
    ref: v0.4.15
    file: '/templates/dockerfile-build.yml'

docker-build:
  before_script:
  - !reference [.docker-config, before_script]
  - ./bin/kitt.sh version > version.txt

variables:
  DOCKER_BUILDKIT: 1
  CODE_QUALITY_DISABLED: "true"
  SAST_DISABLED: "true"
  KYSO_IGNORE_BRANCH: "true"
