= Kyso installation

. Login into *registry.kyso.io* with the provided credentials, running the following command
+
[source,console]
----
$ docker login registry.kyso.io
----

. Configure common properties for Kyso deployment running the following and set
the values shown:
+
[source,console]
----
$ ./kitt.sh apps common env-update
-------------------------------------
Common Settings
-------------------------------------
Space separated list of ingress hostnames [fjbarrena.kyso.io]:
imagePullPolicy ('Always'/'IfNotPresent') [Always]:
Manage TLS certificates for the ingress definitions? (Yes/No) [No]: Yes
Port forward IP address [127.0.0.1]:
-------------------------------------
common configuration saved to '/root/kitt-data/clusters/default/deployments/dev/envs/common.env'
-------------------------------------
----

. Install *MongoDB*
+
[source,console]
----
$ ./kitt.sh apps mongodb install
----

+
[NOTE]
======
Issues? See the troubleshooting section ;)
======

. Install *NATS*
+
[source,console]
----
$ ./kitt.sh apps nats install
----

. Install *ElasticSearch*
+
[source,console]
----
$ ./kitt.sh apps elasticsearch install
----

. Install *Mongo GUI*
+
[source,console]
----
$ ./kitt.sh apps mongo-gui install
----

. *If provided*, execute the script `kyso-exports.sh`. This script will export all the environment variables needed for the next commands. To execute the script run the following command
+
[source,console]
----
$ source kyso-exports.sh
----

. Install *kyso-api*
+
[source,shell]
----
$ ./kitt.sh apps kyso-api install
----
+
[NOTE]
======

If `kyso-exports.sh` was not provided, use the following command specifying the docker image:

[source,console]
----
$ KYSO_API_IMAGE=registry.kyso.io/kyso-io/kyso-api/develop:latest \
  ./kitt.sh apps kyso-api install
----

======

. Configure *kyso-scs* and adjust values depending on your needs and the supported storage classes 

+
[source,console]
----
$ ./kitt.sh apps kyso-scs env-update
-------------------------------------
Update kyso-scs env vars? (Yes/No) [No]: Yes
-------------------------------------
Reading kyso-scs settings
-------------------------------------
Kyso Indexer Endpoint (i.e. '172.17.0.1:8080' or '-' to deploy image) []: 
Indexer Image URI (i.e. 'registry.kyso.io/kyso-io/kyso-indexer/develop:latest' or export KYSO_SCS_INDEXER_IMAGE var) []: 
MySecureShell Image URI [registry.kyso.io/docker/mysecureshell:latest]: 
Nginx Image URI [registry.kyso.io/docker/nginx-scs:latest]: 
Webhook Image URI [registry.kyso.io/docker/webhook-scs:latest]: 
SCS Replicas [1]: 
Kyso SCS Access Modes ('ReadWriteOnce', 'ReadWriteMany' if efs) [ReadWriteOnce]: ReadWriteMany 
Kyso SCS Storage Class ('local-storage' @ k3d, 'efs-sc' @ eks) []: efs-sc
Kyso SCS Volume Size [10Gi]: 
Kyso SCS backups use restic (Yes/No) [No]: 
Kyso SCS Hardlink Cronjob Image URI [registry.kyso.io/docker/alpine:latest]: 
Kyso SCS Hardlink Cronjob Schedule [0 0 * * *]: 
Fixed port for kyso-indexer pf? (i.e. 8080 or '-' for random) []: 
Fixed port for mysecureshell pf? (i.e. 2020 or '-' for random) []: 
Fixed port for webhook pf? (i.e. 9000 or '-' for random) []: 
-------------------------------------
Save updated kyso-scs env vars? (Yes/No) [Yes]: Yes
----

. Install *kyso-scs*

+
[source,console]
----
$ ./kitt.sh apps kyso-scs install
----
+
[NOTE]
======

If `kyso-exports.sh` was not provided, use the following command specifying the docker image

[source,console]
----
$ KYSO_SCS_INDEXER_IMAGE=registry.kyso.io/kyso-io/kyso-indexer/develop:latest \
  ./kitt.sh apps kyso-scs install
----
======

. Install *kyso-front*
+
[source,console]
----
./kitt.sh apps kyso-front install
----
+
[NOTE]
======
If `kyso-exports.sh` was not provided, use the following command specifying the docker image

[source,console]
----
$ KYSO_FRONT_IMAGE=registry.kyso.io/kyso-io/kyso-front/develop:latest \
  ./kitt.sh apps kyso-front install
----
======


. Install *kyso-nbdime* component
+
[source,console]
----
./kitt.sh apps kyso-nbdime install
----
+
[NOTE]
======
If `kyso-exports.sh` was not provided, use the following command specifying the docker image

[source,console]
----
$ KYSO_NBDIME_IMAGE=registry.kyso.io/docker/kyso-nbdime:latest \
  ./kitt.sh apps kyso-nbdime install

----
======



. Install *jupyter-diff* component
+
[source,console]
----
./kitt.sh apps jupyter-diff install
----
+
[NOTE]
======
If `kyso-exports.sh` was not provided, use the following command specifying the docker image

[source,console]
----
$ JUPYTER_DIFF_IMAGE=registry.kyso.io/kyso-io/microfrontends/jupyter-diff/develop:latest \
  ./kitt.sh apps jupyter-diff install
----
======


. Install *consumers*
+
[NOTE]
======

If you are not going to use Microsoft Teams nor Slack integrations, you can skip their installation

The consumers are not mandatory, but if not installed some features wouldn't be available

======
+
[source,console]
----
$ ./kitt.sh apps activity-feed-consumer install
$ ./kitt.sh apps notification-consumer install
$ ./kitt.sh apps slack-notifications-consumer install
$ ./kitt.sh apps teams-notification-consumer install
$ ./kitt.sh apps file-metadata-postprocess-consumer install
$ ./kitt.sh apps analytics-consumer install
----
+
[NOTE]
======
If `kyso-exports.sh` was not provided, use the following commands specifying the docker image

[source,shell]
----
$ ACTIVITY_FEED_CONSUMER_IMAGE=registry.kyso.io/kyso-io/consumers/activity-feed-consumer/develop:latest \
  ./kitt.sh apps activity-feed-consumer install
$ NOTIFICATION_CONSUMER_IMAGE=registry.kyso.io/kyso-io/consumers/notification-consumer/develop:latest \
  ./kitt.sh apps notification-consumer install
$ SLACK_NOTIFICATIONS_CONSUMER_IMAGE=registry.kyso.io/kyso-io/consumers/slack-notifications-consumer/develop:latest \
  ./kitt.sh apps slack-notifications-consumer install
$ TEAMS_NOTIFICATION_CONSUMER_IMAGE=registry.kyso.io/kyso-io/consumers/teams-notification-consumer/develop:latest \
  ./kitt.sh apps teams-notification-consumer install
$ FILE_METADATA_POSTPROCESS_IMAGE=registry.kyso.io/kyso-io/consumers/file-metadata-postprocess/develop:latest \
  ./kitt.sh apps file-metadata-postprocess-consumer install
$ ANALYTICS_CONSUMER_IMAGE=registry.kyso.io/kyso-io/consumers/analytics-consumer:latest \
  ./kitt.sh apps analytics-consumer install
----
======

. Finally, install OnlyOffice server
+
[source,console]
----
$ ./kitt.sh apps onlyoffice-ds install
----

. Check that all the kubernetes pods are running executing the following command:
+
[source,console]
----
$ kubectl get pods -A
NAMESPACE                                 NAME                                                              READY   STATUS      RESTARTS        AGE
nats-dev                                  kyso-nats-box-7db44f66bc-tcf2x                                    1/1     Running     0               341d
activity-feed-consumer-dev                activity-feed-consumer-5f4cc74dc5-6424h                           1/1     Running     0               163d
slack-notifications-consumer-dev          slack-notifications-consumer-645b5bbf58-clhnx                     1/1     Running     0               9d
analytics-consumer-dev                    analytics-consumer-85cc77cf8f-sstpx                               1/1     Running     0               55d
imagebox-dev                              imagebox-d88544db9-krnzf                                          1/1     Running     0               163d
teams-notification-consumer-dev           teams-notification-consumer-f587d498f-lkj68                       1/1     Running     0               9d
file-metadata-postprocess-consumer-dev    file-metadata-postprocess-consumer-6f46c8d8dc-qccc7               1/1     Running     0               79d
nats-dev                                  kyso-nats-0                                                       3/3     Running     0               341d
mongodb-dev                               kyso-mongodb-0                                                    1/1     Running     0               161d
mongo-gui-dev                             mongo-gui-dcb855c46-gdc94                                         1/1     Running     0               163d
kyso-scs-dev                              kyso-scs-0                                                        4/4     Running     0               91d
elasticsearch-dev                         elasticsearch-master-0                                            1/1     Running     0               341d
onlyoffice-ds-dev                         onlyoffice-ds-554f88d446-vk2b2                                    1/1     Running     0               163d
notification-consumer-dev                 notification-consumer-cd89d999-jn7dw                              1/1     Running     0               8d
kyso-api-dev                              kyso-api-68f8d84d58-ftkm5                                         1/1     Running     0               2d16h
jupyter-diff-dev                          jupyter-diff-f89f4fddb-gzkb9                                      1/1     Running     0               15h
kyso-front-dev                            kyso-front-cfcf646f6-qs22p                                        1/1     Running     0               56m
kyso-nbdime-dev                           kyso-nbdime-6c5d568c49-gdhhw                                      1/1     Running     0               115s
----
