#!/bin/sh
# ----
# File:        docker-kitt
# Description: Script to manage the kittcontainter on the developer machine.
# Author:      Sergio Talens-Oliag <sto@kyso.io>
# Copyright:   (c) 2022 Sergio Talens-Oliag <sto@kyso.io>
# ----

set -e

# ---------
# VARIABLES
# ---------

# Relative PATH to the workdir from this script (usually . or .., empty means .)
RELPATH_TO_WORKDIR=".."

# Variables
IMAGE_NAME="kitt"
CONTAINER_NAME="kitt"
BUILD_ARGS=""
CONTAINER_VARS="-v $HOME:$HOME"
CONTAINER_VARS="$CONTAINER_VARS -v /etc/passwd:/etc/passwd:ro"
CONTAINER_VARS="$CONTAINER_VARS -v /etc/group:/etc/group:ro"

# ---------
# FUNCTIONS
# ---------

# POSIX compliant version of readlinkf (MacOS does not have coreutils) copied
# from https://github.com/ko1nksm/readlinkf/blob/master/readlinkf.sh
_readlinkf_posix() {
  [ "${1:-}" ] || return 1
  max_symlinks=40
  CDPATH='' # to avoid changing to an unexpected directory
  target=$1
  [ -e "${target%/}" ] || target=${1%"${1##*[!/]}"} # trim trailing slashes
  [ -d "${target:-/}" ] && target="$target/"
  cd -P . 2>/dev/null || return 1
  while [ "$max_symlinks" -ge 0 ] && max_symlinks=$((max_symlinks - 1)); do
    if [ ! "$target" = "${target%/*}" ]; then
      case $target in
      /*) cd -P "${target%/*}/" 2>/dev/null || break ;;
      *) cd -P "./${target%/*}" 2>/dev/null || break ;;
      esac
      target=${target##*/}
    fi
    if [ ! -L "$target" ]; then
      target="${PWD%/}${target:+/}${target}"
      printf '%s\n' "${target:-/}"
      return 0
    fi
    # `ls -dl` format: "%s %u %s %s %u %s %s -> %s\n",
    #   <file mode>, <number of links>, <owner name>, <group name>,
    #   <size>, <date and time>, <pathname of link>, <contents of link>
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ls.html
    link=$(ls -dl -- "$target" 2>/dev/null) || break
    target=${link#*" $target -> "}
  done
  return 1
}

# Change to working directory (script dir + the value of RELPATH_TO_WORKDIR)
cd_to_workdir() {
  _script="$(_readlinkf_posix "$0")"
  _script_dir="${_script%/*}"
  if [ "$RELPATH_TO_WORKDIR" ]; then
    cd "$(_readlinkf_posix "$_script_dir/$RELPATH_TO_WORKDIR")"
  else
    cd "$_script_dir"
  fi
}

docker_build() {
  PACKAGE_VERSION="$1"
  [ "$PACKAGE_VERSION" ] || PACKAGE_VERSION="latest"
  # Compute build args
  if [ -f "./.build-args" ]; then
    BUILD_ARGS="$(
      awk '!/^#/ { printf(" --build-arg \"%s\"", $0); }' "./.build-args"
    )"
  fi
  BUILD_TAG="$IMAGE_NAME:$PACKAGE_VERSION"
  DOCKER_COMMAND="DOCKER_BUILDKIT=1 docker build${BUILD_ARGS}"
  DOCKER_COMMAND="$DOCKER_COMMAND --tag '$BUILD_TAG' ."
  eval "$DOCKER_COMMAND"
}

docker_build_prune() {
  DOCKER_BUILDKIT=1 docker builder prune -af
}

docker_rm() {
  docker rm "$CONTAINER_NAME"
}

docker_run() {
  PACKAGE_VERSION="$1"
  [ "$PACKAGE_VERSION" ] || PACKAGE_VERSION="latest"
  if [ "$(docker_status)" ]; then
    docker rm "$CONTAINER_NAME"
  fi
  BUILD_TAG="$IMAGE_NAME:$PACKAGE_VERSION"
  DOCKER_COMMAND="$(
    printf "%s" \
      "docker run -ti --rm --name '$CONTAINER_NAME' --network host -w $HOME" \
      " $CONTAINER_VARS '$BUILD_TAG'"
  )"
  eval "$DOCKER_COMMAND"
}

docker_run_as_user() {
  CONTAINER_VARS="$CONTAINER_VARS -u $(id -u):$(id -g)"
  docker_run "$@"
}

docker_status() {
  docker ps -a -f name="${CONTAINER_NAME}" --format '{{.Status}}' 2>/dev/null ||
    true
}

docker_stop() {
  docker stop "$CONTAINER_NAME"
  docker rm "$CONTAINER_NAME"
}

usage() {
  cat <<EOF
Usage: $0 CMND [ARGS]

Where CMND can be one of:
- build: create container using the passed package version
- build-prune: cleanup builder caché
- rar: run container in interactive mode as root
- run: run container in interactive mode with the right settings
- stop|status|rm|logs: operations on the container
EOF
}

# ----
# MAIN
# ----

cd_to_workdir
echo "WORKING DIRECTORY = '$(pwd)'"
echo ""

case "$1" in
build) shift && docker_build "$@";;
build-prune) docker_build_prune ;;
logs) shift && docker_logs "$@" ;;
rm) docker_rm ;;
rar) shift && docker_run "$@" ;;
run) shift && docker_run_as_user "$@";;
status) docker_status ;;
stop) docker_stop ;;
*) usage ;;
esac

# ----
# vim: ts=2:sw=2:et:ai:sts=2
