apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-kyso-mongodb-0
  namespace: mongodb-prod
  labels:
    app.kubernetes.io/name: mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
