#!/bin/sh
# ----
# File:        addons
# Description: Command to manage addons on k8s clusters
# Author:      Sergio Talens-Oliag <sto@kyso.io>
# Copyright:   (c) 2022 Sergio Talens-Oliag <sto@kyso.io>
# ----

set -e

# ---------
# Variables
# ---------

CMND_DSC="addons: manage addons on k8s clusters"

# --------
# Includes
# --------

if [ "$INCL_DIR" ]; then
  # shellcheck source=../incl/addons.sh
  [ "$INCL_ADDONS_SH" = "1" ] || . "$INCL_DIR/addons.sh"
else
  echo "This command has to be executed using kitt.sh"
  exit 1
fi

# ---------
# Functions
# ---------

usage_addons_dsc() {
  _addon="$1"
  if [ -f "$INCL_DIR/addons/$_addon.sh" ]; then
    sed -ne "s/^\( *#.*\|\)CMND_DSC=\"\(.*\)\".*/\2/p" \
      "$INCL_DIR/addons/$_addon.sh"
  else
    echo "$_addon"
  fi
}

# Usage function
usage() {
  _addons_list="$(addons_list)"
  if [ "$_addons_list" ]; then
    _addons_usage_list="$(
      for _a in $_addons_list; do
        echo "  - $(usage_addons_dsc "$_a")";
      done)"
  else
    _addons_usage_list=""
  fi
  _addons_sets="$(addons_sets)"
  if [ "$_addons_sets" ]; then
    _addons_set_usage_list="$(
      for _as in $_addons_sets; do echo "  - $_as"; done
    )"
  else
    _addons_set_usage_list=""
  fi
  cat <<EOF
Command to ${CMND_DSC#*: }.

Usage:

  $APP_BASE_NAME $(basename "$0") TOOL SUBCOMMAND [CLUSTER_NAME]

Where TOOL can be:

$(
  if [ "$_addons_usage_list" ]; then
    echo "- A single add-on:"
    echo ""
    echo "$_addons_usage_list";
    echo ""
    if [ "$_addons_set_usage_list" ]; then
      echo "- A set of add-ons:"
      echo ""
      echo "$_addons_set_usage_list";
      echo ""
    fi
  fi
)

The valid subcommands for each tool are listed passing only the TOOL name.

If CLUSTER_NAME is not passed '$CLUSTER_NAME' is used.
EOF
  exit "$1"
}

usage_addon() {
  _addon="$1"
  cat <<EOF
Subcommand to manage '$_addon' on a kubernetes cluster.

Usage:

  $APP_BASE_NAME $(basename "$0") $_addon SUBCOMMAND [CLUSTER_NAME]

Where SUBCOMMAND is one of:

$(for _cmd in $(addons_command_list "$_addon"); do echo "- $_cmd"; done)

If CLUSTER_NAME is not passed '$CLUSTER_NAME' is used.
EOF
  exit "$2"
}

usage_addons_set() {
  _addons_set="$1"
  cat <<EOF
Subcommand to manage the '$_addons_set' addon set on a kubernetes cluster.

Usage:

  $APP_BASE_NAME $(basename "$0") $_addons_set SUBCOMMAND [CLUSTER_NAME]

The addons included are:

$(
for _a in $(addons_set_list "$_addons_set"); do
  echo "- $(usage_addons_dsc "$_a")";
done
)

And SUBCOMMAND is one of:

$(for _cmd in $(addons_set_command_list "$_addons_set"); do echo "- $_cmd"; done)

If CLUSTER_NAME is not passed '$CLUSTER_NAME' is used.
EOF
  exit "$2"
}

# ----
# MAIN
# ----

_addon=""
for _a in $(addons_list); do
  if [ "$1" = "$_a" ]; then
    _addon="$_a"
    break
  fi
done

_addons_set=""
for _s in $(addons_sets); do
  if [ "$1" = "$_s" ]; then
    _addons_set="$_s"
    break
  fi
done

_command=""
if [ "$_addon" ]; then
  for _c in $(addons_command_list "$_addon"); do
    if [ "$2" = "$_c" ]; then
      _command="$2"
      break
    fi
  done
elif [ "$_addons_set" ]; then
  for _c in $(addons_set_command_list "$_addons_set"); do
    if [ "$2" = "$_c" ]; then
      _command="$2"
      break
    fi
  done
fi

_cluster="$3"
addons_export_variables "$_cluster"

if [ "$_addon" ]; then
  if [ "$_command" ]; then
    addons_command "$_addon" "$_command" "$_cluster"
  else
    usage_addon "$_addon" 0
  fi
elif [ "$_addons_set" ]; then
  if [ "$_command" ]; then
    addons_set_command "$_addons_set" "$_command" "$_cluster"
  else
    usage_addons_set "$_addons_set" 0
  fi
else
  usage 0
fi

# ----
# vim: ts=2:sw=2:et:ai:sts=2
