#!/bin/sh
# ----
# File:        version
# Description: Display kitt version
# Author:      Sergio Talens-Oliag <sto@kyso.io>
# Copyright:   (c) 2022 Sergio Talens-Oliag <sto@kyso.io>
# ----

set -e

# ---------
# Variables
# ---------

# shellcheck disable=SC2034
CMND_DSC="version: display kitt version"

# ----
# MAIN
# ----

_version_file="$INCL_DIR/version.txt"
if [ -f "$_version_file" ]; then
  cat "$_version_file"
else
  _branch="$(git branch --show-current 2>/dev/null)" || true
  _commit="$(git rev-parse HEAD 2>/dev/null)" || true
  _tag="$(git describe --tags "$_commit" 2>/dev/null)" || true
  if [ "$_branch" ] && [ "$_commit" ]; then
    echo "git:"
    echo "  branch: $_branch"
    echo "  commit: $_commit"
    echo "  tag: $_tag"
    if [ "$(git status --porcelain)" ]; then
      echo "  treeStatus: dirty"
    fi
  else
    echo "Unknown"
  fi
fi
# ----
# vim: ts=2:sw=2:et:ai:sts=2
